name: Mark stale issues and pull requests

env:
    CIRRUS_CLONE_DEPTH: 1
    CIRRUS_WORKING_DIR: "/tmp/ci"

task:
  name: master
  timeout_in: 2h
  container:
    image: dopaemon/bionic:latest
    cpu: 8
    memory: 8G

  Install_Packages_Ubuntu_script:
      - rm -rf *
      - apt update && apt-get install -y build-essential bc python curl git zip ftp gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi libssl-dev lftp zstd wget libfl-dev clang flex bison cpio
      - wget https://raw.githubusercontent.com/dinhsan2000/android_kernel_xiaomi_picasso/lineage-18.1/kramel.sh
      - chmod +x kramel.sh
      - bash kramel.sh
