kind: pipeline
name: picasso_kramel

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:
  - name: setup&kramel
    image: dinhsan2000/ci_docker:latest
    environment:
      BOTTOKEN:
        from_secret: 1583001052:AAEdbNvTVclDXq97mCgoHXQQ_76QjviKH8U
      CHATID:
        from_secret: 527634747
    commands:
      - mkdir kernul && cd kernul
      - apt update && apt-get install -y build-essential bc python curl git zip ftp gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi libssl-dev lftp zstd wget libfl-dev clang flex bison cpio
      - wget https://raw.githubusercontent.com/stormbreaker-project/kernel_xiaomi_picasso/rebase/kramel.sh
      - chmod +x kramel.sh
      - bash kramel.sh
